### ISSUE TITLE
Finding a bounding box

### ISSUE THREAD

**Issue by tiagodavi** [pkinney/envelope_ex#5]
Hi. thank you for this amazing library. I would like to know how I can use this library to find a bounding box between 2 pairs of coordinates. Ex I have the input [{lat1, long1}, {lat2,long2}] and would like the bounding box between them as output.

**Comment by pkinney** [comment]
@tiagodavi, you can currently use Envelope to do this by either creating an Envelope and expanding it to the two points:

```
Envelope.empty() |>
Envelope.expand({-90, 30}) |>
Envelope.expand({-91, 32})
```

or creating an Envelope directly from a list of coordinates: 

```
Envelope.from_geo(%{coordinates: [{-90, 30}, {-91, 32}]})
```

P.S. sorry for the (very) late reply.
